### ISSUE TITLE
IDE Fatal Errors

### ISSUE THREAD

**Issue by SergSlon** [axaluss/power-mode-intellij-plugin#11]
Hello, my PhpStorm was broken today after update/

null
java.lang.AssertionError
	at com.intellij.openapi.editor.impl.view.EditorView.getPreferredSize(EditorView.java:255)
	at com.intellij.openapi.editor.impl.EditorImpl.getPreferredSize(EditorImpl.java:3885)
	at de.ax.powermode.power.management.ElementOfPowerContainer.doShake(ElementOfPowerContainer.scala:238)
	at de.ax.powermode.power.management.ElementOfPowerContainer.paintComponent(ElementOfPowerContainer.scala:299)
	at javax.swing.JComponent.paint(JComponent.java:1053)
	at javax.swing.JComponent.paintChildren(JComponent.java:886)
	at javax.swing.JComponent.paint(JComponent.java:1062)
	at com.intellij.openapi.editor.impl.EditorComponentImpl.paint(EditorComponentImpl.java:122)
	at com.intellij.codeInsight.hint.EditorFragmentComponent.a(EditorFragmentComponent.java:119)
	at com.intellij.codeInsight.hint.EditorFragmentComponent.<init>(EditorFragmentComponent.java:53)
	at com.intellij.codeInsight.hint.EditorFragmentComponent.createEditorFragmentComponent(EditorFragmentComponent.java:243)
	at com.intellij.codeInsight.hint.EditorFragmentComponent.showEditorFragmentHintAt(EditorFragmentComponent.java:207)
	at com.intellij.codeInsight.hint.DocumentFragmentTooltipRenderer.show(DocumentFragmentTooltipRenderer.java:80)
	at com.intellij.codeInsight.hint.TooltipController.showTooltip(TooltipController.java:139)
	at com.intellij.codeInsight.hint.TooltipController.showTooltip(TooltipController.java:117)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseMotionListener.mouseMoved(EditorImpl.java:6285)
	at java.awt.Component.processMouseMotionEvent(Component.java:6570)
	at javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3339)
	at java.awt.Component.processEvent(Component.java:6294)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4546)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:719)
	at java.awt.EventQueue$4.run(EventQueue.java:717)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:675)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by axaluss** [comment]
fixed in 
https://github.com/axaluss/power-mode-intellij-plugin/releases/tag/2.8.12
