### ISSUE TITLE
Error when Music Enabled

### ISSUE THREAD

**Issue by JCharante** [axaluss/power-mode-intellij-plugin#15]
I'm running Pycharm EAP 171.3566.25 on Ubuntu 16.04

```
jcharante@brad:~$ java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```

```
jcharante@brad:~$ uname -r
4.4.0-63-generic
```

I have `libavformat-ffmpeg56` and `libavcodec-extra` installed.

The error in the IDE is 

```
error playing file /home/jcharante/Music/test.mp3: com.sun.media.jfxmedia.MediaException: Could not create player!: com.sun.media.jfxmedia.MediaException: Could not create player!
MediaException: UNKNOWN : com.sun.media.jfxmedia.MediaException: Could not create player! : com.sun.media.jfxmedia.MediaException: Could not create player!
	at javafx.scene.media.MediaException.exceptionToMediaException(MediaException.java:146)
	at javafx.scene.media.MediaPlayer.init(MediaPlayer.java:511)
	at javafx.scene.media.MediaPlayer.<init>(MediaPlayer.java:414)
	at de.ax.powermode.power.sound.PowerSound.doPlay(PowerSound.scala:71)
	at de.ax.powermode.power.sound.PowerSound.play(PowerSound.scala:54)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.updateSound(ElementOfPowerContainerManager.scala:70)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.run(ElementOfPowerContainerManager.scala:45)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.sun.media.jfxmedia.MediaException: Could not create player!
	at com.sun.media.jfxmediaimpl.NativeMediaManager.getPlayer(NativeMediaManager.java:274)
	at com.sun.media.jfxmedia.MediaManager.getPlayer(MediaManager.java:118)
	at javafx.scene.media.MediaPlayer.init(MediaPlayer.java:467)
	... 6 more
```

**Comment by axaluss** [comment]
my specs: 
```
~ $ uname -a
.....3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
```
~ $ java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

I guess you need oracle java for  javafx and mp3 support.

**Comment by JCharante** [comment]
Installed Oracle Java. Problem still occurs

```
jcharante@brad:~$ java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

**Comment by axaluss** [comment]
hummmm...
did you install all packages mentioned here?: http://www.oracle.com/technetwork/java/javase/certconfig-2095354.html

```
You must install GLIB 2.28 in order to run JavaFX Media.

You must install the following in order to support
 AAC audio, MP3 audio, H.264 video, and HTTP Live Streaming:

    libavcodec53 and libavformat53 on Ubuntu Linux 12.04 or equivalent.

```

**Comment by JCharante** [comment]
I've installed

```
libavcodec-dev
libglib2.0-0
libglib2.0-dev
libavformat-dev
```

Still get the same error.

```
error playing file /home/jcharante/Music/test.mp3: com.sun.media.jfxmedia.MediaException: Could not create player!: com.sun.media.jfxmedia.MediaException: Could not create player!
MediaException: UNKNOWN : com.sun.media.jfxmedia.MediaException: Could not create player! : com.sun.media.jfxmedia.MediaException: Could not create player!
	at javafx.scene.media.MediaException.exceptionToMediaException(MediaException.java:146)
	at javafx.scene.media.MediaPlayer.init(MediaPlayer.java:511)
	at javafx.scene.media.MediaPlayer.<init>(MediaPlayer.java:414)
	at de.ax.powermode.power.sound.PowerSound.doPlay(PowerSound.scala:71)
	at de.ax.powermode.power.sound.PowerSound.play(PowerSound.scala:54)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.updateSound(ElementOfPowerContainerManager.scala:70)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.run(ElementOfPowerContainerManager.scala:45)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.sun.media.jfxmedia.MediaException: Could not create player!
	at com.sun.media.jfxmediaimpl.NativeMediaManager.getPlayer(NativeMediaManager.java:274)
	at com.sun.media.jfxmedia.MediaManager.getPlayer(MediaManager.java:118)
	at javafx.scene.media.MediaPlayer.init(MediaPlayer.java:467)
	... 6 more
```

**Comment by JCharante** [comment]
After install packages obtained here

https://www.ubuntuupdates.org/package/core/precise/main/updates/libavutil51
https://www.ubuntuupdates.org/package/core/trusty/main/base/libvpx1
https://www.ubuntuupdates.org/package/core/precise/main/security/libavcodec53
https://www.ubuntuupdates.org/package/core/precise/universe/security/libavutil-extra-51
https://www.ubuntuupdates.org/package/core/precise/main/security/libavformat53

I am no longer getting any error and the music is playing.

**Comment by axaluss** [comment]
you can test the sound with this code:

``` java

import javafx.embed.swing.JFXPanel;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;

import java.io.File;
 
public class SoundTest {
    public static void main(String[] args) {
        File f = new File("/home/nyxos/Music/Amazing_Horse.mp3");
        JFXPanel jfxPanel = new JFXPanel();
        Media hit = new Media(f.toURI().toString());
        MediaPlayer mediaPlayer = new MediaPlayer(hit);
        mediaPlayer.setVolume(1.0);
        mediaPlayer.play();
        System.out.println("playing");
        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        mediaPlayer.stop();
        System.out.println("stopping");
         mediaPlayer.dispose();
    }
}

```

**Comment by axaluss** [comment]
you can test the sound with this code:

``` java

import javafx.embed.swing.JFXPanel;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;

import java.io.File;
 
public class SoundTest {
    public static void main(String[] args) {
        File f = new File(replace with test mp3 "/home/nyxos/Music/Amazing_Horse.mp3");
        JFXPanel jfxPanel = new JFXPanel();
        Media hit = new Media(f.toURI().toString());
        MediaPlayer mediaPlayer = new MediaPlayer(hit);
        mediaPlayer.setVolume(1.0);
        mediaPlayer.play();
        System.out.println("playing");
        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        mediaPlayer.stop();
        System.out.println("stopping");
         mediaPlayer.dispose();
    }
}

```

**Comment by axaluss** [comment]
I was able to reproduce this bug locally. It started working when I edited idea.sh to use oracle java to start.
