### ISSUE TITLE
Bug on new file php in Phpstorm

### ISSUE THREAD

**Issue by ROKAISAKKON** [axaluss/power-mode-intellij-plugin#21]
I can't typing in input on new php file box.

`Argument for @NotNull parameter 'project' of com/intellij/openapi/fileEditor/FileEditorManager.getInstance must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'project' of com/intellij/openapi/fileEditor/FileEditorManager.getInstance must not be null
	at com.intellij.openapi.fileEditor.FileEditorManager.getInstance(FileEditorManager.java)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anonfun$showIndicator$1.apply(ElementOfPowerContainerManager.scala:60)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anonfun$showIndicator$1.apply(ElementOfPowerContainerManager.scala:59)
	at scala.Option.foreach(Option.scala:257)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager.showIndicator(ElementOfPowerContainerManager.scala:59)
	at de.ax.powermode.PowerMode$$anonfun$increaseHeatup$1$$anonfun$apply$1.apply(PowerMode.scala:116)
	at de.ax.powermode.PowerMode$$anonfun$increaseHeatup$1$$anonfun$apply$1.apply(PowerMode.scala:116)
	at scala.Option.foreach(Option.scala:257)
	at de.ax.powermode.PowerMode$$anonfun$increaseHeatup$1.apply(PowerMode.scala:116)
	at de.ax.powermode.PowerMode$$anonfun$increaseHeatup$1.apply(PowerMode.scala:116)
	at scala.Option.foreach(Option.scala:257)
	at de.ax.powermode.PowerMode.increaseHeatup(PowerMode.scala:116)
	at de.ax.powermode.MyTypedActionHandler.execute(MyTypedActionHandler.scala:19)
	at com.intellij.openapi.editor.actionSystem.TypedAction.lambda$actionPerformed$0(TypedAction.java:136)
	at com.intellij.reporting.FreezeLoggerImpl.runUnderPerformanceMonitor(FreezeLoggerImpl.java:42)
	at com.intellij.openapi.editor.actionSystem.TypedAction.actionPerformed(TypedAction.java:136)
	at com.intellij.openapi.editor.impl.EditorImpl.b(EditorImpl.java:1202)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:5486)
	at com.intellij.openapi.editor.impl.EditorImpl$8.keyTyped(EditorImpl.java:1037)
	at java.awt.Component.processKeyEvent(Component.java:6490)
`

**Comment by axaluss** [comment]
fixed in 2.12.12
