### ISSUE TITLE
NullPointerException in WebStorm

### ISSUE THREAD

**Issue by apaatsio** [axaluss/power-mode-intellij-plugin#24]
I was editing code and got a notification in WebStorm that this error happened. I didn't notice any actual problem in the UI, though, and Power Mode seemed to continue to work.

WebStorm: 2017.1.1 (build 171.4073.40)
PowerMode: 2.12.12

```
<null> 
java.lang.NullPointerException
	at de.ax.powermode.power.element.PowerIndicator$$anonfun$isLast$1.apply(PowerIndicator.scala:85)
	at de.ax.powermode.power.element.PowerIndicator$$anonfun$isLast$1.apply(PowerIndicator.scala:85)
	at scala.Option.exists(Option.scala:240)
	at de.ax.powermode.power.element.PowerIndicator.isLast(PowerIndicator.scala:85)
	at de.ax.powermode.power.element.PowerIndicator.life(PowerIndicator.scala:75)
	at de.ax.powermode.power.ElementOfPower$class.alive(ElementOfPower.scala:25)
	at de.ax.powermode.power.element.PowerIndicator.alive(PowerIndicator.scala:62)
	at de.ax.powermode.power.element.PowerIndicator.update(PowerIndicator.scala:99)
	at de.ax.powermode.power.management.ElementOfPowerContainer$$anonfun$updateElementsOfPower$1.apply(ElementOfPowerContainer.scala:121)
	at de.ax.powermode.power.management.ElementOfPowerContainer$$anonfun$updateElementsOfPower$1.apply(ElementOfPowerContainer.scala:121)
	at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:259)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:258)
	at scala.collection.TraversableLike$class.filterNot(TraversableLike.scala:278)
	at scala.collection.AbstractTraversable.filterNot(Traversable.scala:104)
	at de.ax.powermode.power.management.ElementOfPowerContainer.updateElementsOfPower(ElementOfPowerContainer.scala:121)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1$$anonfun$updateContainers$1.apply(ElementOfPowerContainerManager.scala:94)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1$$anonfun$updateContainers$1.apply(ElementOfPowerContainerManager.scala:94)
	at scala.collection.mutable.HashMap$$anon$2$$anonfun$foreach$3.apply(HashMap.scala:108)
	at scala.collection.mutable.HashMap$$anon$2$$anonfun$foreach$3.apply(HashMap.scala:108)
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
	at scala.collection.mutable.HashMap$$anon$2.foreach(HashMap.scala:108)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.updateContainers(ElementOfPowerContainerManager.scala:94)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.run(ElementOfPowerContainerManager.scala:78)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by axaluss** [comment]
fixed in 3.14.159
