### ISSUE TITLE
NullPointerException with version 3.14.1592

### ISSUE THREAD

**Issue by TrashF** [axaluss/power-mode-intellij-plugin#27]
<null> 
java.lang.NullPointerException
	at de.ax.powermode.power.element.PowerIndicator.$anonfun$isLast$2(PowerIndicator.scala:85)
	at de.ax.powermode.power.element.PowerIndicator.$anonfun$isLast$2$adapted(PowerIndicator.scala:85)
	at scala.Option.exists(Option.scala:240)
	at de.ax.powermode.power.element.PowerIndicator.isLast(PowerIndicator.scala:85)
	at de.ax.powermode.power.element.PowerIndicator.life(PowerIndicator.scala:75)
	at de.ax.powermode.power.ElementOfPower.lifeFactor(ElementOfPower.scala:21)
	at de.ax.powermode.power.ElementOfPower.lifeFactor$(ElementOfPower.scala:20)
	at de.ax.powermode.power.element.PowerIndicator.lifeFactor(PowerIndicator.scala:62)
	at de.ax.powermode.power.element.PowerIndicator.update(PowerIndicator.scala:90)
	at de.ax.powermode.power.management.ElementOfPowerContainer.$anonfun$updateElementsOfPower$1(ElementOfPowerContainer.scala:116)
	at de.ax.powermode.power.management.ElementOfPowerContainer.$anonfun$updateElementsOfPower$1$adapted(ElementOfPowerContainer.scala:116)
	at scala.collection.TraversableLike.$anonfun$filterImpl$1(TraversableLike.scala:248)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:104)
	at scala.collection.AbstractTraversable.filterNot(Traversable.scala:104)
	at de.ax.powermode.power.management.ElementOfPowerContainer.updateElementsOfPower(ElementOfPowerContainer.scala:116)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateContainers$1(ElementOfPowerContainerManager.scala:94)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateContainers$1$adapted(ElementOfPowerContainerManager.scala:94)
	at scala.collection.mutable.HashMap$$anon$2.$anonfun$foreach$3(HashMap.scala:108)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
	at scala.collection.mutable.HashMap$$anon$2.foreach(HashMap.scala:108)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.updateContainers(ElementOfPowerContainerManager.scala:94)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.run(ElementOfPowerContainerManager.scala:78)
	at java.lang.Thread.run(Thread.java:745)

**Comment by axaluss** [comment]
fixed in 3.14.15926
