### ISSUE TITLE
Enabling music crashes / causes bugs.

### ISSUE THREAD

**Issue by EntranceJew** [axaluss/power-mode-intellij-plugin#28]
I've experimented with trying to get JFX enabled or making sure that the correct folder path was being supplied but basically after putting in 4 hours to the cause, I have absolutely no idea what is being asked of me to make the music happen.

When it is enabled and I hit ctrl+shift+alt+m to switch tracks it freezes jetbrains and it produces a log file about every 4 seconds from the folder I've attached here: [threadDumps-freeze-20170624-200129-RS-171.4456.575.zip](https://github.com/axaluss/power-mode-intellij-plugin/files/1100056/threadDumps-freeze-20170624-200129-RS-171.4456.575.zip)

When I type it does not create any errors in any logs I have found, but the particles do not display in full and they linger until they despawn:
![pixel floats](https://i.imgur.com/bfUDwn6.png)

I tried, I just couldn't get it to work. Which kinda sucks because I wanted to jam out to some of [hackmud's music](https://radicaldreamland.bandcamp.com/track/electroheist).

**Comment by axaluss** [comment]
Settings info: `!Music requires jfx installed and on IDE classpath!`

How to do this?
There is a file `idea.sh`.
in there around 
```
CLASSPATH="$IDE_HOME/lib/bootstrap.jar"
CLASSPATH="$CLASSPATH:$IDE_HOME/lib/extensions.jar"
CLASSPATH="$CLASSPATH:$IDE_HOME/lib/util.jar"
CLASSPATH="$CLASSPATH:$IDE_HOME/lib/jdom.jar"
CLASSPATH="$CLASSPATH:$IDE_HOME/lib/log4j.jar"
CLASSPATH="$CLASSPATH:$IDE_HOME/lib/trove4j.jar"
CLASSPATH="$CLASSPATH:$IDE_HOME/lib/jna.jar"
CLASSPATH="$CLASSPATH:$JDK/lib/tools.jar"
```
There you can add the path to jfx jar.

**Comment by EntranceJew** [comment]
I tried to do this today, only using `phpstorm.bat` because of the jetbrains toolbox installation. I copied the `jfxrt.jar` from my jre8 folder, and no matter which way I ran the batch file I ended up getting this error as soon as i enabled `play music`:

```
java.lang.ClassCastException: com.sun.glass.ui.win.WinPlatformFactory cannot be cast to com.sun.glass.ui.PlatformFactory
        at com.sun.glass.ui.PlatformFactory.getPlatformFactory(PlatformFactory.java:43)
        at com.sun.glass.ui.Application.run(Application.java:146)
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:257)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:211)
        at javafx.embed.swing.JFXPanel.initFx(JFXPanel.java:215)
        at javafx.embed.swing.JFXPanel.<init>(JFXPanel.java:230)
        at de.ax.powermode.power.sound.PowerSound.doPlay(PowerSound.scala:66)
        at de.ax.powermode.power.sound.PowerSound.play(PowerSound.scala:52)
        at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$2(ElementOfPowerContainerManager.scala:102)
        at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$2$adapted(ElementOfPowerContainerManager.scala:102)
        at scala.util.Success.foreach(Try.scala:249)
        at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.updateSound(ElementOfPowerContainerManager.scala:102)
        at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.run(ElementOfPowerContainerManager.scala:77)
        at java.lang.Thread.run(Thread.java:745)
Failed to load Glass factory class
```

The only other log file reference I could find was:
```
2017-06-26 12:49:41,482 [  66922]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE SHUTDOWN ------------------------------------------------------ 
2017-06-26 12:49:41,486 [  66926]   INFO - org.jetbrains.io.BuiltInServer - web server stopped 
2017-06-26 12:49:41,488 [  66928]  ERROR -      de.ax.powermode.PowerMode -  
java.lang.NullPointerException
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.run(ElementOfPowerContainerManager.scala:80)
	at java.lang.Thread.run(Thread.java:745)
```

Does this mean that if this does work, that I have to launch it from the batch file instead of the toolbox?

**Comment by EntranceJew** [comment]
The toolbox bundles each app with its own java version, inside /jre64, there doesn't exist `jfxrt.jar`, only `lib/jfxwrt.jar`, `bin/jfxmedia.dll` and `bin/jfxwebkit.dll`. As far as I can tell, it will always prefer the version of java it ships with and installing JFX on Windows is not easy. 

`/jre64/release` contains:
```
JAVA_VERSION="1.8.0_112"
OS_NAME="Windows"
OS_VERSION="5.2"
OS_ARCH="amd64"
SOURCE=""
```

It could be using the OpenJRE/JDK instead of Oracle packages, or the other way around. I wouldn't know first-hand how to check.

**Comment by axaluss** [comment]
This is really strange..
http://grepcode.com/file/repo1.maven.org/maven2/net.java.openjfx.backport/openjfx-78-backport/1.8.0-ea-b96.1/com/sun/glass/ui/PlatformFactory.java

It tries to load WinPlatformFactory which should implement that PlatformFactory 
https://github.com/barchart/barchart-javafx-study/blob/master/barchart-oracle-javafx-2.2.7/src/main/java/com/sun/glass/ui/win/WinPlatformFactory.java

**Comment by axaluss** [comment]
Music works perfectly on my machine
