### ISSUE TITLE
Got error while deleting

### ISSUE THREAD

**Issue by ejdunn2001** [axaluss/power-mode-intellij-plugin#34]
javax.imageio.IIOException: Can't get input stream from URL!
	at javax.imageio.ImageIO.read(ImageIO.java:1395)
	at de.ax.powermode.ImageUtil$.$anonfun$getImagesCached$2(ImageUtil.scala:52)
	at de.ax.powermode.cache.Cache.getOrUpdate(Cache.scala:22)
	at de.ax.powermode.ImageUtil$.$anonfun$getImagesCached$1(ImageUtil.scala:51)
	at scala.collection.immutable.List.flatMap(List.scala:335)
	at de.ax.powermode.ImageUtil$.getImagesCached(ImageUtil.scala:50)
	at de.ax.powermode.ImageUtil$.images(ImageUtil.scala:37)
	at de.ax.powermode.ImageUtil$.$anonfun$imagesForPath$3(ImageUtil.scala:17)
	at scala.Option.map(Option.scala:146)
	at de.ax.powermode.ImageUtil$.$anonfun$imagesForPath$2(ImageUtil.scala:17)
	at de.ax.powermode.cache.Cache.getOrUpdate(Cache.scala:22)
	at de.ax.powermode.ImageUtil$.imagesForPath(ImageUtil.scala:17)
	at de.ax.powermode.power.element.PowerBam.update(PowerBam.scala:28)
	at de.ax.powermode.power.management.ElementOfPowerContainer.$anonfun$updateElementsOfPower$1(ElementOfPowerContainer.scala:116)
	at de.ax.powermode.power.management.ElementOfPowerContainer.$anonfun$updateElementsOfPower$1$adapted(ElementOfPowerContainer.scala:116)
	at scala.collection.TraversableLike.$anonfun$filterImpl$1(TraversableLike.scala:248)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:247)
	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:104)
	at scala.collection.TraversableLike.filterNot(TraversableLike.scala:267)
	at scala.collection.TraversableLike.filterNot$(TraversableLike.scala:267)
	at scala.collection.AbstractTraversable.filterNot(Traversable.scala:104)
	at de.ax.powermode.power.management.ElementOfPowerContainer.updateElementsOfPower(ElementOfPowerContainer.scala:116)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateContainers$1(ElementOfPowerContainerManager.scala:95)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateContainers$1$adapted(ElementOfPowerContainerManager.scala:95)
	at scala.collection.mutable.HashMap$$anon$2.$anonfun$foreach$3(HashMap.scala:147)
	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:236)
	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:229)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
	at scala.collection.mutable.HashMap$$anon$2.foreach(HashMap.scala:147)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.updateContainers(ElementOfPowerContainerManager.scala:95)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.run(ElementOfPowerContainerManager.scala:79)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: /var/folders/rh/c1c39ht128x71jq6jbj29trn21h5hd/T/1535656419629_pmtempfile_1091989936145078990.png (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at java.net.URL.openStream(URL.java:1045)
	at javax.imageio.ImageIO.read(ImageIO.java:1393)
	... 33 more

**Comment by axaluss** [comment]
Try the new release: [12.56](https://github.com/axaluss/power-mode-intellij-plugin/releases/tag/12.56)
I added more info to the log. I suspect the URL is invalid or you used a web URL, which I think wont work.
