### ISSUE TITLE
NoClassDefFoundError 

### ISSUE THREAD

**Issue by Ernest-su** [axaluss/power-mode-intellij-plugin#35]
java.lang.NoClassDefFoundError: 
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: 
	at de.ax.powermode.power.sound.PowerSound.doStop(PowerSound.scala:37)
	at de.ax.powermode.power.sound.PowerSound.stop(PowerSound.scala:49)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3$adapted(ElementOfPowerContainerManager.scala:105)
	at scala.util.Success.foreach(Try.scala:249)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.updateSound(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.run(ElementOfPowerContainerManager.scala:78)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: 
	... 8 more

java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: 
	at de.ax.powermode.power.sound.PowerSound.doStop(PowerSound.scala:37)
	at de.ax.powermode.power.sound.PowerSound.stop(PowerSound.scala:49)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3$adapted(ElementOfPowerContainerManager.scala:105)
	at scala.util.Success.foreach(Try.scala:249)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.updateSound(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.run(ElementOfPowerContainerManager.scala:78)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: 
	... 8 more

java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: 
	at de.ax.powermode.power.sound.PowerSound.doStop(PowerSound.scala:37)
	at de.ax.powermode.power.sound.PowerSound.stop(PowerSound.scala:49)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3$adapted(ElementOfPowerContainerManager.scala:105)
	at scala.util.Success.foreach(Try.scala:249)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.updateSound(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.run(ElementOfPowerContainerManager.scala:78)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: 
	... 8 more

java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: 
	at de.ax.powermode.power.sound.PowerSound.doStop(PowerSound.scala:37)
	at de.ax.powermode.power.sound.PowerSound.stop(PowerSound.scala:49)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3$adapted(ElementOfPowerContainerManager.scala:105)
	at scala.util.Success.foreach(Try.scala:249)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.updateSound(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.run(ElementOfPowerContainerManager.scala:78)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: 
	... 8 more

java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: 
	at de.ax.powermode.power.sound.PowerSound.doStop(PowerSound.scala:37)
	at de.ax.powermode.power.sound.PowerSound.stop(PowerSound.scala:49)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3$adapted(ElementOfPowerContainerManager.scala:105)
	at scala.util.Success.foreach(Try.scala:249)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.updateSound(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.run(ElementOfPowerContainerManager.scala:78)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: 
	... 8 more

java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: 
	at de.ax.powermode.power.sound.PowerSound.doStop(PowerSound.scala:37)
	at de.ax.powermode.power.sound.PowerSound.stop(PowerSound.scala:49)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3$adapted(ElementOfPowerContainerManager.scala:105)
	at scala.util.Success.foreach(Try.scala:249)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.updateSound(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.run(ElementOfPowerContainerManager.scala:78)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: 
	... 8 more

java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: 
	at de.ax.powermode.power.sound.PowerSound.doStop(PowerSound.scala:37)
	at de.ax.powermode.power.sound.PowerSound.stop(PowerSound.scala:49)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3$adapted(ElementOfPowerContainerManager.scala:105)
	at scala.util.Success.foreach(Try.scala:249)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.updateSound(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.run(ElementOfPowerContainerManager.scala:78)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: 
	... 8 more

java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: 
	at de.ax.powermode.power.sound.PowerSound.doStop(PowerSound.scala:37)
	at de.ax.powermode.power.sound.PowerSound.stop(PowerSound.scala:49)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3$adapted(ElementOfPowerContainerManager.scala:105)
	at scala.util.Success.foreach(Try.scala:249)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.updateSound(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.run(ElementOfPowerContainerManager.scala:78)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: 
	... 8 more

java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: 
	at de.ax.powermode.power.sound.PowerSound.doStop(PowerSound.scala:37)
	at de.ax.powermode.power.sound.PowerSound.stop(PowerSound.scala:49)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3$adapted(ElementOfPowerContainerManager.scala:105)
	at scala.util.Success.foreach(Try.scala:249)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.updateSound(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.run(ElementOfPowerContainerManager.scala:78)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: 
	... 8 more

java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: 
	at de.ax.powermode.power.sound.PowerSound.doStop(PowerSound.scala:37)
	at de.ax.powermode.power.sound.PowerSound.stop(PowerSound.scala:49)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3$adapted(ElementOfPowerContainerManager.scala:105)
	at scala.util.Success.foreach(Try.scala:249)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.updateSound(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.run(ElementOfPowerContainerManager.scala:78)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: 
	... 8 more

java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: 
	at de.ax.powermode.power.sound.PowerSound.doStop(PowerSound.scala:37)
	at de.ax.powermode.power.sound.PowerSound.stop(PowerSound.scala:49)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3$adapted(ElementOfPowerContainerManager.scala:105)
	at scala.util.Success.foreach(Try.scala:249)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.updateSound(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.run(ElementOfPowerContainerManager.scala:78)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: 
	... 8 more

java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: 
	at de.ax.powermode.power.sound.PowerSound.doStop(PowerSound.scala:37)
	at de.ax.powermode.power.sound.PowerSound.stop(PowerSound.scala:49)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3$adapted(ElementOfPowerContainerManager.scala:105)
	at scala.util.Success.foreach(Try.scala:249)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.updateSound(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.run(ElementOfPowerContainerManager.scala:78)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: 
	... 8 more

java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: 
	at de.ax.powermode.power.sound.PowerSound.doStop(PowerSound.scala:37)
	at de.ax.powermode.power.sound.PowerSound.stop(PowerSound.scala:49)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3$adapted(ElementOfPowerContainerManager.scala:105)
	at scala.util.Success.foreach(Try.scala:249)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.updateSound(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.run(ElementOfPowerContainerManager.scala:78)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: 
	... 8 more

java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: 
	at de.ax.powermode.power.sound.PowerSound.doStop(PowerSound.scala:37)
	at de.ax.powermode.power.sound.PowerSound.stop(PowerSound.scala:49)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3$adapted(ElementOfPowerContainerManager.scala:105)
	at scala.util.Success.foreach(Try.scala:249)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.updateSound(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.run(ElementOfPowerContainerManager.scala:78)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: 
	... 8 more

java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: 
	at de.ax.powermode.power.sound.PowerSound.doStop(PowerSound.scala:37)
	at de.ax.powermode.power.sound.PowerSound.stop(PowerSound.scala:49)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3$adapted(ElementOfPowerContainerManager.scala:105)
	at scala.util.Success.foreach(Try.scala:249)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.updateSound(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.run(ElementOfPowerContainerManager.scala:78)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: 
	... 8 more

java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: 
	at de.ax.powermode.power.sound.PowerSound.doStop(PowerSound.scala:37)
	at de.ax.powermode.power.sound.PowerSound.stop(PowerSound.scala:49)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3$adapted(ElementOfPowerContainerManager.scala:105)
	at scala.util.Success.foreach(Try.scala:249)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.updateSound(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.run(ElementOfPowerContainerManager.scala:78)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: 
	... 8 more

java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: 
	at de.ax.powermode.power.sound.PowerSound.doStop(PowerSound.scala:37)
	at de.ax.powermode.power.sound.PowerSound.stop(PowerSound.scala:49)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3$adapted(ElementOfPowerContainerManager.scala:105)
	at scala.util.Success.foreach(Try.scala:249)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.updateSound(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.run(ElementOfPowerContainerManager.scala:78)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: 
	... 8 more

java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: 
	at de.ax.powermode.power.sound.PowerSound.doStop(PowerSound.scala:37)
	at de.ax.powermode.power.sound.PowerSound.stop(PowerSound.scala:49)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3$adapted(ElementOfPowerContainerManager.scala:105)
	at scala.util.Success.foreach(Try.scala:249)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.updateSound(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.run(ElementOfPowerContainerManager.scala:78)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: 
	... 8 more

java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: 
	at de.ax.powermode.power.sound.PowerSound.doStop(PowerSound.scala:37)
	at de.ax.powermode.power.sound.PowerSound.stop(PowerSound.scala:49)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3$adapted(ElementOfPowerContainerManager.scala:105)
	at scala.util.Success.foreach(Try.scala:249)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.updateSound(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.run(ElementOfPowerContainerManager.scala:78)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: 
	... 8 more

java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: 
	at de.ax.powermode.power.sound.PowerSound.doStop(PowerSound.scala:37)
	at de.ax.powermode.power.sound.PowerSound.stop(PowerSound.scala:49)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3$adapted(ElementOfPowerContainerManager.scala:105)
	at scala.util.Success.foreach(Try.scala:249)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.updateSound(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.run(ElementOfPowerContainerManager.scala:78)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: 
	... 8 more

**Comment by Ernest-su** [comment]
I have unchecked the sound option，in this case I still need javafx library?

**Comment by axaluss** [comment]
No then you dont need it. What version of intellij and powermode are you using?

**Comment by Ernest-su** [comment]
Android Studio 3.2
Build #AI-181.5540.7.32.5014246, built on September 18, 2018
JRE: 1.8.0_152-release-1136-b06 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

powermode Ⅱ 12.56

**Comment by axaluss** [comment]
I also need the steps to reproduce the problem.

**Comment by Ernest-su** [comment]
I just  unchecked the PLAY MUSIC option, just open Android Studio，the exception happen.

**Comment by yurihan** [comment]
I have same problem.

```
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: 
	at de.ax.powermode.power.sound.PowerSound.doStop(PowerSound.scala:37)
	at de.ax.powermode.power.sound.PowerSound.stop(PowerSound.scala:49)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateSound$3$adapted(ElementOfPowerContainerManager.scala:105)
	at scala.util.Success.foreach(Try.scala:249)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.updateSound(ElementOfPowerContainerManager.scala:105)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.run(ElementOfPowerContainerManager.scala:78)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: 
	... 8 more
```

```
Android Studio 3.2.1
Build #AI-181.5540.7.32.5056338, built on October 9, 2018
JRE: 1.8.0_152-release-1136-b06 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

powermode Ⅱ 12.56

macOS Mojave 10.14
```
