### ISSUE TITLE
Error reading image from uri: 

### ISSUE THREAD

**Issue by crucifyer** [axaluss/power-mode-intellij-plugin#37]
`Error reading image from uri: 'file:/C:/Users/devuser/AppData/Local/Temp/1545638998665_pmtempfile_6964067312776197384.png' url: 'Success(file:/C:/Users/devuser/AppData/Local/Temp/1545638998665_pmtempfile_6964067312776197384.png)': Can't get input stream from URL! 

javax.imageio.IIOException: Can't get input stream from URL!
	at javax.imageio.ImageIO.read(ImageIO.java:1395)
	at de.ax.powermode.ImageUtil$.$anonfun$getImagesCached$2(ImageUtil.scala:62)
	at de.ax.powermode.cache.Cache.getOrUpdate(Cache.scala:22)
	at de.ax.powermode.ImageUtil$.$anonfun$getImagesCached$1(ImageUtil.scala:61)
	at scala.collection.immutable.List.flatMap(List.scala:335)
	at de.ax.powermode.ImageUtil$.getImagesCached(ImageUtil.scala:59)
	at de.ax.powermode.ImageUtil$.images(ImageUtil.scala:42)
	at de.ax.powermode.ImageUtil$.$anonfun$imagesForPath$3(ImageUtil.scala:20)
	at scala.Option.map(Option.scala:146)
	at de.ax.powermode.ImageUtil$.$anonfun$imagesForPath$2(ImageUtil.scala:20)
	at de.ax.powermode.cache.Cache.getOrUpdate(Cache.scala:22)
	at de.ax.powermode.ImageUtil$.imagesForPath(ImageUtil.scala:20)
	at de.ax.powermode.power.element.PowerBam.update(PowerBam.scala:33)
	at de.ax.powermode.power.management.ElementOfPowerContainer.$anonfun$updateElementsOfPower$1(ElementOfPowerContainer.scala:130)
	at de.ax.powermode.power.management.ElementOfPowerContainer.$anonfun$updateElementsOfPower$1$adapted(ElementOfPowerContainer.scala:130)
	at scala.collection.TraversableLike.$anonfun$filterImpl$1(TraversableLike.scala:248)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:247)
	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:104)
	at scala.collection.TraversableLike.filterNot(TraversableLike.scala:267)
	at scala.collection.TraversableLike.filterNot$(TraversableLike.scala:267)
	at scala.collection.AbstractTraversable.filterNot(Traversable.scala:104)
	at de.ax.powermode.power.management.ElementOfPowerContainer.updateElementsOfPower(ElementOfPowerContainer.scala:130)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateContainers$1(ElementOfPowerContainerManager.scala:106)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.$anonfun$updateContainers$1$adapted(ElementOfPowerContainerManager.scala:106)
	at scala.collection.mutable.HashMap$$anon$2.$anonfun$foreach$3(HashMap.scala:147)
	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:236)
	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:229)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
	at scala.collection.mutable.HashMap$$anon$2.foreach(HashMap.scala:147)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.updateContainers(ElementOfPowerContainerManager.scala:106)
	at de.ax.powermode.power.management.ElementOfPowerContainerManager$$anon$1.run(ElementOfPowerContainerManager.scala:92)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: C:\Users\devuser\AppData\Local\Temp\1545638998665_pmtempfile_6964067312776197384.png (지정된 파일을 찾을 수 없습니다)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at java.net.URL.openStream(URL.java:1045)
	at javax.imageio.ImageIO.read(ImageIO.java:1393)
	... 33 more`

**Comment by axaluss** [comment]
This looks like a temp file. You should save all your photos into folders
and copy that folder path into the config textbox. Also make sure the
access rights are good.
