### ISSUE TITLE
Can't type ! or ?

### ISSUE THREAD

**Issue by matkoch** [axaluss/power-mode-intellij-plugin#39]
Having enabled power mode, I can't type `!` or `?`... didn't check other symbols.

**Comment by axaluss** [comment]
What's your IDE version and OS? Other plugins enabled?

**Comment by matkoch** [comment]
```
JetBrains Rider 2018.3.3
Build #RD-183.5619.41, built on February 8, 2019
Licensed to Nuke / Matthias Koch
Subscription is active until May 31, 2019
For non-commercial open source development only.
JRE: 1.8.0_152-release-1343-b26 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.1
```

No suspicious plugins I'd say. Also, as mentioned, disabling powermode fixes it.
<img width="639" alt="image" src="https://user-images.githubusercontent.com/5005566/54311674-65378a00-45d5-11e9-8a19-ad9a0dd47eac.png">

**Comment by matkoch** [comment]
Disabled all plugins, same behavior.

But I do have a stacktrace for you :)

> java.lang.ClassCastException: com.intellij.openapi.actionSystem.KeyboardModifierGestureShortcut$DblClick cannot be cast to com.intellij.openapi.actionSystem.KeyboardShortcut
	at de.ax.powermode.power.hotkeys.HotkeyHeatupListener.$anonfun$actionsToKeyStrokes$5(HotkeyHeatupListener.scala:54)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at de.ax.powermode.power.hotkeys.HotkeyHeatupListener.$anonfun$actionsToKeyStrokes$3(HotkeyHeatupListener.scala:54)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at de.ax.powermode.power.hotkeys.HotkeyHeatupListener.actionsToKeyStrokes$lzycompute(HotkeyHeatupListener.scala:51)
	at de.ax.powermode.power.hotkeys.HotkeyHeatupListener.actionsToKeyStrokes(HotkeyHeatupListener.scala:46)
	at de.ax.powermode.power.hotkeys.HotkeyHeatupListener.allActionKeyStrokes$lzycompute(HotkeyHeatupListener.scala:22)
	at de.ax.powermode.power.hotkeys.HotkeyHeatupListener.allActionKeyStrokes(HotkeyHeatupListener.scala:21)
	at de.ax.powermode.power.hotkeys.HotkeyHeatupListener.eventDispatched(HotkeyHeatupListener.scala:32)
	at java.awt.Toolkit$SelectiveAWTEventListener.eventDispatched(Toolkit.java:2430)
	at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2322)
	at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2321)
	at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2321)
	at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2321)
	at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2321)
	at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2321)
	at java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2321)
	at java.awt.Toolkit.notifyAWTEventListeners(Toolkit.java:2280)
	at java.awt.Component.dispatchEventImpl(Component.java:4799)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:27)
	at java.awt.Component.dispatchEventImpl(Component.java:4774)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:646)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by axaluss** [comment]
try https://github.com/axaluss/power-mode-intellij-plugin/releases/tag/97.68
