### ISSUE TITLE
java.lang.UnsupportedOperationException: empty.maxBy

### ISSUE THREAD

**Issue by dragisak** [axaluss/power-mode-intellij-plugin#9]
I am seeing this error with latest version of plugin (2.8.6)

IntelliJ IDEA 2016.3.2
Build #IU-163.10154.41, built on December 21, 2016

Mac OSX

```
empty.maxBy
java.lang.UnsupportedOperationException: empty.maxBy
	at scala.collection.TraversableOnce$class.maxBy(TraversableOnce.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.maxBy(ArrayOps.scala:186)
	at de.ax.powermode.power.management.ElementOfPowerContainer$$anon$1.documentChanged(ElementOfPowerContainer.scala:97)
```

**Comment by axaluss** [comment]
fixed in 2.8.8
